config/routes.rb
# require 'sidekiq/web'
# Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

Rails.application.routes.draw do

  # authenticate :user do
  #   mount Sidekiq::Web => '/jobs'
  # end

  root 'dashboard#index'

  devise_for :users
  # resources :users

  resources :applications do
    resources :work_managers, except: [:index] do
      member do
        get :check
        delete :clear_cycles
      end
    end
  end


end

app/models/work_manager.rb
class WorkManager < ApplicationRecord
  extend Enumerize

  belongs_to :application
  has_many :cycles, dependent: :destroy

  scope :active, -> { where(active: true) }

  validates :name, :aws_region, :autoscalinggroup_name, :queue_name, :max_workers, :min_workers, :minutes_to_process, :jobs_per_cycle, :application, presence: true

  enumerize :active, in: [true, false]

  before_save :default_values
  def default_values
    # self.last_check ||= Time.now
  end

  after_save :verify_changes
  def verify_changes
    self.cycles.destroy_all if self.queue_name_previously_changed?
  end

  def to_s
    name
  end

  def total_intervals_period?
    (self.minutes_to_process.to_f / CheckService.cycle_interval.to_f).ceil
  end

  def viable?
    aws_region.present? && autoscalinggroup_name.present? && application.jobs_url.present?
  end

  def jobs_count
    jobs = JobsService.new(self.application.jobs_url).queue_jobs(self.queue_name)
    jobs[:total_jobs]
  rescue => e
    0
  end

  def workers_count
    AwsService.new(self.cycles.last).total_instances
  end

end

app/controllers/work_managers_controller.rb
class WorkManagersController < ApplicationController

  before_action :set_application
  before_action :set_work_manager, only: [:show, :edit, :update, :destroy, :active, :check, :clear_cycles]

  def show
  end

  def new
    @work_manager = @application.work_managers.new
  end

  def edit
  end

  def create
    @work_manager = @application.work_managers.new(work_manager_params)
    @work_manager.save
    respond_with(@application, @work_manager)
  end

  def update
    @work_manager.update(work_manager_params)
    respond_with(@application, @work_manager)
  end

  def destroy
    @work_manager.destroy
    respond_with(@application, @work_manager, location: application_path(@application))
  end

  def check
    begin
      CheckService.new(@work_manager).check
      flash[:success] = 'Checagem Efetuada!'
    rescue => e
      flash[:error] = 'Ocorreu um erro ao tentar efetuar a checagem: %s' % e.message
    end
    redirect_to [@application, @work_manager]
  end

  def clear_cycles
    @work_manager.cycles.destroy_all
    respond_with(@application, @work_manager)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_work_manager
    @work_manager = @application.work_managers.find(params[:id])
  end

  def set_application
    @application = Application.find(params[:application_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def work_manager_params
    params.require(:work_manager).permit(:id, :name, :aws_region, :autoscalinggroup_name, :queue_name, :max_workers, :min_workers, :minutes_to_process, :jobs_per_cycle, :active)
  end

end

app/views/work_managers/_form.html.haml
= simple_form_for [@application, @work_manager], html: {class: 'form form-horizontal form-bordered'}, wrapper: :horizontal_form do |f|
  .form-body
    = f.input :name
    = f.input :aws_region
    = f.input :autoscalinggroup_name
    = f.input :queue_name
    = f.input :max_workers
    = f.input :min_workers
    = f.input :minutes_to_process
    = f.input :jobs_per_cycle
    = f.input :active, include_blank: false
  .form-actions
    = f.submit class: 'btn btn-primary'

app/views/work_managers/_item.html.haml
.card
  .card-header
    %h4.card-title= @work_manager.name
    .heading-elements
      .btn-group{"aria-label" => "Basic example", :role => "group"}
        = link_to edit_application_work_manager_path(@application, @work_manager), class: 'btn btn-sm btn-outline-secondary', title: 'Editar' do
          %i.fa.fa-edit
          = t(:edit)
        = link_to application_work_manager_path(@application, @work_manager), method: :delete, data: {confirm: t(:are_you_sure)}, class: 'btn btn-sm btn-outline-danger', title: 'Excluir' do
          %i.fa.fa-trash
          = t(:destroy)
  .card-content
    .card-body.pt-0
      %p.card-text
        %strong= WorkManager.human_attribute_name(:name)
        %br
        = @work_manager.name
      %p.card-text
        %strong= WorkManager.human_attribute_name(:autoscalinggroup_name)
        %br
        = @work_manager.autoscalinggroup_name
      %p.card-text
        %strong= WorkManager.human_attribute_name(:aws_region)
        %br
        = @work_manager.aws_region
      %p.card-text
        %strong= WorkManager.human_attribute_name(:queue_name)
        %br
        = @work_manager.queue_name
      %p.card-text
        %strong= WorkManager.human_attribute_name(:max_workers)
        %br
        = @work_manager.max_workers
      %p.card-text
        %strong= WorkManager.human_attribute_name(:min_workers)
        %br
        = @work_manager.min_workers
      %p.card-text
        %strong= WorkManager.human_attribute_name(:minutes_to_process)
        %br
        = @work_manager.minutes_to_process
      %p.card-text
        %strong= WorkManager.human_attribute_name(:jobs_per_cycle)
        %br
        = @work_manager.jobs_per_cycle
      %p.card-text
        %strong= WorkManager.human_attribute_name(:last_check)
        %br
        = l(@work_manager.last_check, format: :short) if @work_manager.last_check.present?
      - if @work_manager.last_error.present?
        %p.card-text
          %strong= WorkManager.human_attribute_name(:last_error)
          .text-danger= @work_manager.last_error
      %p.card-text
        %strong= WorkManager.human_attribute_name(:active)
        %br
        = @work_manager.active_text

app/views/work_managers/_last_cycles.html.haml
.card
  .card-header
    %h4.card-title= t(:last_cycles)
    .heading-elements
      .btn-group
        = link_to '#', data: {action: 'expand'}, class: 'btn btn-sm btn-outline-secondary' do
          %i.ft-maximize
          = t(:expand)
        - if defined?(application) && defined?(work_manager)
          = link_to check_application_work_manager_path(application, work_manager), data: {confirm: t(:are_you_sure), disable_with: t(:running)}, class: 'btn btn-sm btn-outline-warning', title: 'Forçar Checagem' do
            %i.fa.fa-bolt
            = t(:check)
          = link_to clear_cycles_application_work_manager_path(application, work_manager), method: :delete, data: {confirm: t(:are_you_sure), disable_with: t(:running)}, class: 'btn btn-sm btn-outline-danger', title: 'Excluir Todos os Ciclos' do
            %i.fa.fa-trash
            = t(:clear)

  .card-content.collapse.show
    - if defined?(cycles) && cycles.recent.count > 0
      .table-responsive
        %table.table.table-hover.table-striped.mb-0
          %thead
            %tr
              - if defined?(application) && !defined?(worker_manager)
                %th= Cycle.human_attribute_name(:work_manager)
              %th= Cycle.human_attribute_name(:queue_jobs)
              %th= Cycle.human_attribute_name(:new_jobs)
              %th= Cycle.human_attribute_name(:processed_jobs)
              %th= Cycle.human_attribute_name(:workers)
              %th= Cycle.human_attribute_name(:updated_at)
          %tbody
            - cycles.last_cycles.each do |cycle|
              %tr
                - if defined?(application) && !defined?(worker_manager)
                  %td= link_to cycle.work_manager.name, [application, cycle.work_manager]
                %td= cycle.queue_jobs
                %td= cycle.new_jobs
                %td= cycle.processed_jobs
                %td
                  #{cycle.current_workers} => #{cycle.workers} (#{cycle.desired_workers})
                %td
                  = time_ago_in_words cycle.updated_at
                  atrás
    - else
      .card-body.pt-0
        .alert.alert-info= t(:no_records_found)

app/views/work_managers/edit.html.haml
.content-wrapper
  .content-header.row
    .content-header-left.col-md-6.col-12.mb-2
      %h3.content-header-title.mb-0
        = t(:edit)
        = WorkManager.model_name.human
    .content-header-right.text-md-right.col-md-6.col-12
      .btn-group
        = link_to application_path(@application), class: 'btn btn-sm btn-secondary' do
          = Application.model_name.human
          = @application.name
  .content-body
    %section
      .row
        .col-md-12
          .card
            .card-content.collpase.show
              .card-body
                = render 'form'

app/views/work_managers/new.html.haml
.content-wrapper
  .content-header.row
    .content-header-left.col-md-6.col-12.mb-2
      %h3.content-header-title.mb-0
        = t(:new)
        = WorkManager.model_name.human
    .content-header-right.text-md-right.col-md-6.col-12
      .btn-group
        = link_to application_path(@application), class: 'btn btn-sm btn-secondary' do
          = Application.model_name.human
          = @application.name
  .content-body
    %section
      .row
        .col-md-12
          .card
            .card-content.collpase.show
              .card-body
                = render 'form'

app/views/work_managers/show.html.haml
.content-wrapper
  .content-header.row
    .content-header-left.col-md-6.col-12.mb-2
      %h3.content-header-title.mb-0
        = WorkManager.model_name.human
        = @work_manager.name
    .content-header-right.text-md-right.col-md-6.col-12
      .btn-group
        = link_to application_path(@application), class: 'btn btn-sm btn-secondary' do
          = Application.model_name.human
          = @application.name
  .content-body
    %section.row
      .col-md-6.col-lg-4
        = render 'item'
      .col-md-6.col-lg-8
        = render 'last_cycles', application: @application, work_manager: @work_manager, cycles: @work_manager.cycles