config/routes.rb
# require 'sidekiq/web'
# Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]

Rails.application.routes.draw do

  # authenticate :user do
  #   mount Sidekiq::Web => '/jobs'
  # end

  root 'dashboard#index'

  devise_for :users
  # resources :users

  resources :applications do
    resources :work_managers, except: [:index] do
      member do
        get :check
        delete :clear_cycles
      end
    end
  end


end

app/models/application.rb
class Application < ApplicationRecord

  has_many :work_managers, dependent: :destroy
  has_many :cycles, through: :work_managers

  validates :name, :aws_access_key_id, :aws_secret_access_key, :jobs_url, presence: true
  before_save :validate_aws_credentials, :validate_jobs_url

  def validate_aws_credentials
    begin
      AwsService.validate_credentials aws_access_key_id, aws_secret_access_key
      self[:valid_aws_credentials] = true
    rescue Aws::Errors::ServiceError,
        Aws::AutoScaling::Errors::ServiceError => e
      class_path = e.class.to_s.split('::').join('.').underscore
      locale_message_path = I18n.t(class_path, default: nil)
      errors.add(:aws_access_key_id, locale_message_path || e.message)
      errors.add(:aws_secret_access_key, locale_message_path || e.message)
      self[:valid_aws_credentials] = false
    end
  end

  def validate_jobs_url
    begin
      JobsService.new(jobs_url).validate
      self[:valid_jobs_url] = true
    rescue JobsService::InvalidJobUrlGateway => e
      errors.add(:jobs_url, I18n.t(:invalid_jobs_url))
      self[:valid_jobs_url] = false
    rescue  => e
      errors.add(:jobs_url, e.message)
      self[:valid_jobs_url] = false
    end
  end

  def to_s
    name
  end

  def self.status
    apps = []
    self.order(:name).each do |app|
      app.work_managers.each do |work_mgr|
        apps << {
            name: app.name,
            queue: work_mgr.name,
            jobs: work_mgr.jobs_count,
            workers: work_mgr.workers_count
        }
      end
    end
    apps
  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  before_action :set_responders, unless: :devise_controller?

  private
  def set_responders
    self.class.responder = ApplicationResponder
    self.class.respond_to :html, :json, :js
  end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  before_action :set_application, only: [:show, :edit, :update, :destroy]

  def index
    @applications = Application.order(:name)
  end

  def show
  end

  def new
    @application = Application.new
  end

  def edit
  end

  def create
    @application = Application.new(application_params)
    @application.save
    respond_with @application
  end

  def update
    @application.update(application_params)
    respond_with @application
  end

  def destroy
    @application.destroy
    respond_with @application
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_application
    @application = Application.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def application_params
    params.require(:application).permit(:id, :name, :aws_access_key_id, :aws_secret_access_key, :jobs_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon_classes_ok
    'fa-check text-success'
  end

  def icon_classes_error
    'fa-exclamation-triangle text-danger'
  end

  def bootstrap_class_for(flash_type)
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end

end

app/views/applications/_form.html.haml
= simple_form_for @application, html: {class: 'form form-horizontal form-bordered'}, wrapper: :horizontal_form do |f|
  .form-body
    = f.input :name
    = f.input :aws_access_key_id
    = f.input :aws_secret_access_key
    = f.input :jobs_url
  .form-actions
    = f.submit class: 'btn btn-primary'

app/views/applications/_instructions.html.haml
%h4 Instruções

%p
  Crie em seu aplicativo uma API para responder ao ASWorker.
  No caso de um aplicativo ROR, veja o exemplo abaixo onde criamos um controller para um app usando o Delayd Jobs.
%p
  crie um arquivo
  %i controllers/delayed_jobs_controller.rb

%pre
  :plain
    class DelayedJobsController < ApplicationController

      skip_before_action :authenticate_user!

      def index
        render inline: 'ok'
      end

      def info
        # datetime.iso8601
        # 2018-08-21T19:21:56-03:00
        queue_name = params[:queue_name]
        date_time = DateTime.parse(params[:date_time])
        total_jobs= worker_queue_jobs(queue_name)
        new_jobs = worker_new_jobs_since(queue_name, date_time)
        render json: { total_jobs: total_jobs, new_jobs: new_jobs }
      rescue => e
        render json: { error: e.message }
      end

      private

      def worker_source(queue_name)
        Delayed::Job.where('last_error IS NULL').where(queue: queue_name)
      end

      def worker_queue_jobs(queue_name)
        worker_source(queue_name).count(:id)
      end

      def worker_new_jobs_since(queue_name, initial_date_time)
        return 0 unless initial_date_time
        worker_source(queue_name).where('delayed_jobs.created_at > ?', initial_date_time).count(:id)
      end

    end


%p
  No arquivo
  %i config/routes.rb
  adicione as rotas para esses novos actions desse controller


%pre
  :plain
    # Verifica existencia do servico
    get 'delayed_jobs', to: 'delayed_jobs#index'
    # Retorna contadores de Jobs
    get 'delayed_jobs/:queue_name/:date_time', to: 'delayed_jobs#info'

app/views/applications/_item.html.haml
.card
  .card-header
    %h4.card-title= link_to application.name, application
    .heading-elements
      .btn-group{"aria-label" => "Basic example", :role => "group"}
        = link_to edit_application_path(application), class: 'btn btn-sm btn-outline-secondary', title: 'Editar' do
          %i.fa.fa-edit
          = t(:edit)
        = link_to application_path(application), method: :delete, data: {confirm: t(:are_you_sure)}, class: 'btn btn-sm btn-outline-danger', title: 'Excluir' do
          %i.fa.fa-trash
          = t(:destroy)
  .card-content
    .card-body.pt-0
      %p.card-text
        %i.fa{class: application.valid_aws_credentials? ? icon_classes_ok : icon_classes_error}
        = Application.human_attribute_name(:valid_aws_credentials)
      %p.card-text
        %i.fa{class: application.valid_jobs_url? ? icon_classes_ok : icon_classes_error}
        = Application.human_attribute_name(:valid_jobs_url)

app/views/applications/_work_managers.html.haml
.card
  .card-header
    .pull-right
      = link_to new_application_work_manager_path(@application), class: 'btn btn-sm btn-outline-primary', title: 'Novo' do
        %i.fa.fa-plus
        = t(:new)
    %h5.card-title= WorkManager.model_name.human(count: 2)
  .card-content
    - if @application.work_managers.count > 0
      .table-responsive
        %table.table.table-striped.mb-0
          %tbody
            - @application.work_managers.each do |work_manager|
              %tr
                %td.pl-1= link_to work_manager.name, [@application, work_manager]
                %td.pr-0{width: '10'}
                  .btn-group
                    = link_to edit_application_work_manager_path(@application, work_manager), class: 'btn btn-sm btn-outline-secondary' do
                      %i.fa.fa-edit
                      = t(:edit)
                    = link_to application_work_manager_path(@application, work_manager), method: :delete, data: {confirm: t(:are_you_sure)}, title: 'Excluir', class: 'btn btn-sm btn-outline-danger' do
                      %i.fa.fa-trash
                      = t(:destroy)
    - else
      .card-body.pt-0
        .alert.alert-info= t(:no_records_found)

app/views/applications/edit.html.haml
.content-wrapper
  .content-header.row
    .content-header-left.col-md-6.col-12.mb-2
      %h3.content-header-title.mb-0
        = t(:edit)
        = Application.model_name.human
    .content-header-right.text-md-right.col-md-6.col-12
      .btn-group
        = link_to applications_path, class: 'btn btn-sm btn-secondary' do
          %i.fa.arrow-left
          = Application.model_name.human(count: 2)
  .content-body
    %section
      .row
        .col-md-12
          .card
            .card-content.collpase.show
              .card-body
                = render 'form'

app/views/applications/index.html.haml
.content-wrapper
  .content-header.row
    .content-header-left.col-md-6.col-12.mb-2
      %h3.content-header-title.mb-0= Application.model_name.human(count: 2)
    .content-header-right.text-md-right.col-md-6.col-12
      .btn-group
        = link_to new_application_path, class: 'btn btn-sm btn-primary' do
          %i.fa.fa-plus
          = t(:new)
  .content-body
    %section.card-headings
      .row
        - @applications.each do |application|
          .col-sm-6.col-lg-4= render 'item', application: application

app/views/applications/new.html.haml
.content-wrapper
  .content-header.row
    .content-header-left.col-md-6.col-12.mb-2
      %h3.content-header-title.mb-0
        = t(:new)
        = Application.model_name.human
    .content-header-right.text-md-right.col-md-6.col-12
      .btn-group
        = link_to applications_path, class: 'btn btn-sm btn-secondary' do
          %i.fa.arrow-left
          = Application.model_name.human(count: 2)
  .content-body
    %section
      .row
        .col-md-12
          .card
            .card-content.collpase.show
              .card-body
                = render 'form'
      .card
        .card-content
          .card-body
            = render 'instructions'

app/views/applications/show.html.haml
.content-wrapper
  .content-header.row
    .content-header-left.col-md-6.col-12.mb-2
      %h3.content-header-title.mb-0
        = Application.model_name.human
        = @application.name
    .content-header-right.text-md-right.col-md-6.col-12
      .btn-group
        = link_to applications_path, class: 'btn btn-sm btn-secondary' do
          %i.fa.arrow-left
          = Application.model_name.human(count: 2)
  .content-body
    %section.row
      .col-md-6.col-lg-4
        = render 'item', application: @application
        = render 'work_managers'
      .col-md-6.col-lg-8
        = render 'work_managers/last_cycles', application: @application, cycles: @application.cycles